name: Generate

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    timeout-minutes: 10
    steps:
      - name: Generate contribtuions (light & dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contributions.svg
            dist/contributions-dark.svg?palette=github-dark

      - name: Get contributions width
        id: contrubutions
        run: |
          WIDTH=$(grep -o 'width="[^"]*"' dist/contributions.svg | head -1 | grep -o '[0-9]*')
          echo "width=$WIDTH" >> $GITHUB_OUTPUT
      
      - name: Generate statistics (light)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_border=true&theme=default&hide_title=true&card_width=${{ steps.contrubutions.outputs.width }}&hide_rank=true&show_icons=true
          path: dist/statistics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate statistics (dark)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_border=true&theme=github_dark&hide_title=true&card_width=${{ steps.contrubutions.outputs.width }}&hide_rank=true&show_icons=true
          path: dist/statistics-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
