name: Generate

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    timeout-minutes: 10
    steps:
      - name: Generate contribtuions (light & dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contributions-light.svg
            dist/contributions-dark.svg?palette=github-dark
      
      - name: Generate statistics (light)
        uses: cicirello/user-statistician@v1
        with:
          image-file: dist/statistics-light.svg
          animated-language-chart: true
          colors: light
          image-width: '100%'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate statistics (dark)
        uses: cicirello/user-statistician@v1
        with:
          image-file: dist/statistics-dark.svg
          animated-language-chart: true
          colors: dark
          image-width: '100%'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
